force-app/main/default/objects/Assigned_Membership_Promotion__c/Assigned_Membership_Promotion__c.object-meta.xml
<CustomObject>
    <description>Junction object to assign membership promotions to membership types</description>
    <label>Assigned Membership Promotion</label>
    <nameField>
        <displayFormat>AMP-{00000}</displayFormat>
        <label>Assigned Membership Promotions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Membership Promotions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Membership_Promotion__c/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Membership Type</label>
    <referenceTo>TREX1__Membership_Type__c</referenceTo>
    <relationshipName>Assigned_Membership_Promotions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TA_AMP_BlockUpdate.cls
public with sharing class TA_AMP_BlockUpdate implements TriggerAction.BeforeUpdate {

    @TestVisible
    private static final String AMP_UPDATE_EXCEPTION = 'Assigned Membership Promotion records should not be updated. Use the Manage Assignments flow to delete and create new assignments.';

    private Map<Id, Assigned_Membership_Promotion__c> oldMap;

    public void beforeUpdate(
        List<Assigned_Membership_Promotion__c> newList,
        List<Assigned_Membership_Promotion__c> oldList
    ) {
        this.oldMap = new Map<Id, Assigned_Membership_Promotion__c>(oldList);
        for (Assigned_Membership_Promotion__c amp : newList) {
            if (assignmentHasChanged(amp)) {
                amp.addError(AMP_UPDATE_EXCEPTION);
            }
        }
    }

    private Boolean assignmentHasChanged(Assigned_Membership_Promotion__c amp) {
        return amp.Membership_Type__c != this.oldMap.get(amp.Id).Membership_Type__c;
    }

}